package com.nkh1987.rest_postgresql.model;

import jakarta.persistence.*;

@Entity
@Table(name = "students")
public class Student {
    // Id column in SQL table which is autogenerated by RDBMS
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Other SQL table columns
    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "email")
    private String email;

    //no-argument constructor
    public Student() {
    }

    //parametric constructor
    public Student(String firstName, String lastName, String email) {

        super();
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    // getters ans setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
